services:
  postgres:
    image: postgres:16-alpine
    container_name: quik-tech-db
    environment:
      POSTGRES_DB: quik-tech
      POSTGRES_USER: quik-tech
      POSTGRES_PASSWORD: quik-tech123
    ports:
      - "5432:5432"
    volumes:
      - quik-tech_data:/var/lib/postgresql/data

volumes:
  quik-tech_data:
