services:
  postgres:
    image: postgres:16-alpine
    container_name: quiktech-pos-db
    environment:
      POSTGRES_DB: quiktech-pos
      POSTGRES_USER: quiktech-pos
      POSTGRES_PASSWORD: quiktech-pos123
    ports:
      - "5432:5432"
    volumes:
      - quiktech-pos_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: quiktech-pos-redis
    ports:
      - "6379:6379"

volumes:
  quiktech-pos_data:
