spring.application.name=omniflow-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/omniflow
spring.datasource.username=omniflow
spring.datasource.password=omniflow123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
